language: python
python:
  - 3.6

before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda update --yes -q conda -c conda-forge
  - conda config --set always_yes true
  - conda config --set anaconda_upload no

install:
  - conda install -q python=$TRAVIS_PYTHON_VERSION conda-build pip anaconda-client 
  - conda build conda-recipe
  - conda env create -n test-env --file dev/environment-dev.yaml
  - conda install -n test-env --use-local zerrv

script:
  - source activate test-env
  - pytest tests
