
{% set data = load_setup_py_data() %}

package:
  name: zerrv
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - zerrv
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest tests
    - zerrv --help

about:
  home: TODO
  summary: python server to expose zarr volumes
